/**
 * GuidePanel — contextual help panel with technical details.
 * Shows model descriptions, benchmark values, and formula reminders.
 */
import React, { useState } from 'react'

const MODEL_GUIDES = {
  A1: {
    title: 'A1 — Promo Uplift',
    description: 'Models the incremental orders generated by a promotional campaign, including fatigue decay and post-promo residual effects.',
    inputs: [
      { name: 'orders_base_weekly', type: 'float', desc: 'Baseline weekly orders before the promotion' },
      { name: 'promo_type', type: 'enum', desc: 'Type of promotion determines cost structure and benchmark uplift' },
      { name: 'uplift_pct', type: 'float [0-500]', desc: 'Percentage increase in orders during promo weeks' },
      { name: 'duration_weeks', type: 'int [1-52]', desc: 'How long the promotion runs' },
      { name: 'target_segment', type: 'enum', desc: 'User segment being targeted (determines penetration rate)' },
      { name: 'who_funds', type: 'enum', desc: 'Cost allocation between platform and merchant' },
      { name: 'fatigue_curve', type: 'List[float]', desc: 'Optional per-week multipliers overriding default fatigue' },
    ],
    benchmarks: [
      { metric: 'discount_pct uplift', range: '15–40%', mid: '27.5%' },
      { metric: 'bogo uplift', range: '25–50%', mid: '37.5%' },
      { metric: 'free_delivery uplift', range: '20–35%', mid: '27.5%' },
      { metric: 'cashback uplift', range: '8–20%', mid: '14%' },
    ],
  },
  A2: {
    title: 'A2 — Restaurant Acquisition',
    description: 'Cohort-based model tracking each batch of onboarded restaurants through their maturation curve. Supports churn and onboarding promos.',
    inputs: [
      { name: 'restaurant_plan', type: 'List[int]', desc: 'Number of restaurants added per week (0-indexed)' },
      { name: 'restaurant_type', type: 'enum', desc: 'Determines default maturation curve and steady state' },
      { name: 'steady_state_orders', type: 'float', desc: 'Orders/week at full maturity per restaurant' },
      { name: 'churn_rate', type: 'float [0-1]', desc: 'Fraction of restaurants that churn after churn_week' },
      { name: 'churn_week', type: 'int', desc: 'Week after joining when churn is applied' },
    ],
    benchmarks: [
      { metric: 'dark_kitchen_large steady', range: '180–250 orders/wk', mid: '215' },
      { metric: 'traditional_avg steady', range: '40–90 orders/wk', mid: '60' },
      { metric: 'restaurant churn (annual)', range: '10–30%', mid: '20%' },
      { metric: 'onboarding uplift', range: '20–65%', mid: '40%' },
    ],
  },
  A3: {
    title: 'A3 — Cannibalization',
    description: 'Estimates the fraction of new restaurant orders that cannibalize existing GMV rather than generating net-new demand.',
    inputs: [
      { name: 'cannibalization_rate', type: 'float [0-1]', desc: 'Override the default rate for restaurant type' },
    ],
    benchmarks: [
      { metric: 'dark_kitchen cannibalization', range: '5–12%', mid: '8%' },
      { metric: 'traditional_avg', range: '7–18%', mid: '12%' },
      { metric: 'grocery', range: '2–9%', mid: '5%' },
    ],
  },
  A4: {
    title: 'A4 — Seasonality',
    description: 'Applies multiplicative seasonal factors from country-specific holiday calendar, rain season, pay cycles, and temperature effects.',
    inputs: [
      { name: 'country', type: 'enum [17 LATAM]', desc: 'Country determines all default seasonal patterns' },
      { name: 'trend_weekly_growth', type: 'float', desc: 'Underlying organic weekly growth rate (compound)' },
      { name: 'holiday_overrides', type: 'Dict[str, float]', desc: 'Override specific holiday effect values' },
    ],
    benchmarks: [
      { metric: 'Día de las Madres (MX)', range: 'uplift: +37.5%', mid: '+37.5%' },
      { metric: 'Fiestas Patrias (CL)', range: 'uplift: +40%', mid: '+40%' },
      { metric: 'MX rainy season net', range: '+6–10%', mid: '+7.5%' },
      { metric: 'Quincena uplift (MX)', range: '+10–15%', mid: '+12.5%' },
    ],
  },
  B1: {
    title: 'B1 — Unit Economics',
    description: 'Per-order P&L model computing gross revenue, variable costs, and contribution margin for each forecast week.',
    inputs: [
      { name: 'commission_pct', type: 'float [0-1]', desc: 'Platform take rate on GMV' },
      { name: 'avg_order_value', type: 'float [$]', desc: 'Average order value in USD' },
      { name: 'courier_cost_per_order', type: 'float [$]', desc: 'Total courier payout (base + incentives)' },
      { name: 'ad_revenue_per_order', type: 'float [$]', desc: 'Restaurant ads / sponsored listing revenue' },
    ],
    benchmarks: [
      { metric: 'commission (LATAM)', range: '22–32%', mid: '27%' },
      { metric: 'courier cost/order', range: '$3–$6', mid: '$4' },
      { metric: 'contribution margin', range: '-5% to +18%', mid: '+8%' },
    ],
  },
  B2: {
    title: 'B2 — Scenarios & Sensitivity',
    description: 'Generates upside/downside scenario bands and a tornado chart showing which inputs have the largest impact on total orders.',
    inputs: [
      { name: 'upside_multiplier', type: 'float', desc: 'Multiplier for optimistic scenario (e.g. 1.2 = +20%)' },
      { name: 'downside_multiplier', type: 'float', desc: 'Multiplier for pessimistic scenario (e.g. 0.8 = -20%)' },
      { name: 'sensitivity_range_pct', type: 'float', desc: 'Range for tornado sensitivity (±N%)' },
    ],
    benchmarks: [],
  },
  C1: {
    title: 'C1 — Market Share',
    description: 'Models how platform market share evolves over the forecast horizon, scaling total orders accordingly.',
    inputs: [
      { name: 'current_share', type: 'float [0-1]', desc: 'Current platform market share' },
      { name: 'target_share', type: 'float [0-1]', desc: 'Target market share by end of horizon' },
      { name: 'total_market_orders_weekly', type: 'float', desc: 'Total market TAM in weekly orders' },
    ],
    benchmarks: [],
  },
}

export default function GuidePanel({ activeModel, benchmarks }) {
  const [expanded, setExpanded] = useState(true)
  const guide = activeModel ? MODEL_GUIDES[activeModel] : null

  if (!guide && !activeModel) {
    return (
      <div className="ds-card p-4 text-sm text-gray-500">
        Select a model to see documentation.
      </div>
    )
  }

  if (!guide) return null

  return (
    <div className="ds-card overflow-hidden text-xs">
      <div
        className="flex items-center justify-between px-4 py-2 bg-gray-900/80 cursor-pointer
                   border-b border-gray-800"
        onClick={() => setExpanded(e => !e)}
      >
        <span className="font-medium text-gray-300">{guide.title}</span>
        <span className="text-gray-600">{expanded ? '▼' : '▶'}</span>
      </div>

      {expanded && (
        <div className="p-4 space-y-4">
          <p className="text-gray-400 leading-relaxed">{guide.description}</p>

          {guide.inputs.length > 0 && (
            <div>
              <div className="ds-section-header -mx-4 mb-2">Inputs</div>
              <div className="space-y-2">
                {guide.inputs.map(inp => (
                  <div key={inp.name} className="flex gap-2">
                    <span className="font-mono text-blue-400 shrink-0">{inp.name}</span>
                    <span className="text-gray-600">[{inp.type}]</span>
                    <span className="text-gray-500">{inp.desc}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {guide.benchmarks.length > 0 && (
            <div>
              <div className="ds-section-header -mx-4 mb-2">Benchmarks</div>
              <div className="space-y-1">
                {guide.benchmarks.map(b => (
                  <div key={b.metric} className="flex items-center gap-2">
                    <span className="text-gray-500 grow">{b.metric}</span>
                    <span className="font-mono text-gray-400">{b.range}</span>
                    <span className="ds-badge-blue">{b.mid}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
